name: Build and Deploy Azure Function App - Flex Consumption

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # or whatever version you're using

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ntt-car-cd-i1-d
          package: .
          publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISH_PROFILE_CD }}
          sku: 'flexconsumption'
