name: Build and Deploy Azure Function App - Flex Consumption

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or whatever version you're using

      - name: Install dependencies into local folder
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Prepare zip package
        run: |
          mkdir -p build
          cp -r .python_packages build/
          cp -r MyFunction build/
          cp host.json build/
          cp requirements.txt build/
          cd build
          zip -r ../functionapp.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: myfunc-app1
          path: |
            functionapp.zip

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ntt-cad-car-damage-v1
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4255937AC76849E988F83550F2E5FB7F }}
          sku: 'flexconsumption'
